# Generated by Django 5.1.1 on 2024-10-11 16:17

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_cancha', '0003_reservas_tipocancha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField(default=django.utils.timezone.now)),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('estado', models.CharField(default='pendiente', max_length=10)),
                ('cancha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cancha.tipocancha')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_cancha.registro')),
            ],
            options={
                'ordering': ['fecha_reserva'],
            },
        ),
        migrations.DeleteModel(
            name='Reservas',
        ),
    ]
